### ISSUE TITLE
AE2 and ThaumicTinkerer can't work together

### ISSUE THREAD

**Issue by SnoIcarus** [xsun2001/Applied-Energistics-2-Unofficial#1]
AE2 and ThaumicTinkerer can't work together

ThaumicTinkerer version: 2.5-1.7.10-164(lastest)
AE2 version:rv3-beta-7(lastest)

Crash report:
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 17-2-17 下午11:35
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: appeng.api.util.IConfigManager.registerSetting(Lappeng/api/config/Settings;Ljava/lang/Enum;)V
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: appeng.api.util.IConfigManager.registerSetting(Lappeng/api/config/Settings;Ljava/lang/Enum;)V
	at appeng.core.AEConfig.<init>(AEConfig.java:137)
	at appeng.core.AppEng.preInit(AppEng.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 291077744 bytes (277 MB) / 1087373312 bytes (1037 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 1 total; -Xmx8192M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCH	appliedenergistics2-core{rv3-beta-7} [Applied Energistics 2 Core] (minecraft.jar) 
	UCH	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCH	Thaumcraft{4.2.3.5} [Thaumcraft] ([神秘]Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCE	appliedenergistics2{rv3-beta-7} [Applied Energistics 2] (appliedenergistics2-rv3-beta-7.jar) 
	UCH	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] ([神秘附属工匠]ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCH	DummyCore{1.13} [DummyCore] (DummyCore1.13.jar) 
	UCH	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.57' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	AE2 Version: beta rv3-beta-7 for Forge 10.13.4.1448

**Comment by xsun2001** [comment]
明天我会尝试修复它，高中可是很累的。。不过再请你确认一下是不是其他mod导致了这个问题，因为我并没有记得更改过崩溃日志上的那个方法，按理说是不会发生这种事的。

**Comment by MoeHero** [comment]
curse上的tt不是最新的 最新的tt可以用

**Comment by MoeHero** [comment]
前段时间有个ci我下载的 现在那个网站貌似也关了= =我现在用的tt是508

**Comment by SnoIcarus** [comment]
我曹怎么全是国人，吗吓我一套，

**Comment by SnoIcarus** [comment]
你说的那个TT在哪？@MoeHero  我去下载

**Comment by SnoIcarus** [comment]
@xsun2001 好的好的，感谢~~！！

**Comment by xsun2001** [comment]
@SnoIcarus 你所使用的TT不会引发此问题。请再次检查。
![36](https://cloud.githubusercontent.com/assets/14010993/23101614/920d72be-f6d2-11e6-934e-406b8438ea26.png)
![37](https://cloud.githubusercontent.com/assets/14010993/23101613/920c5352-f6d2-11e6-9de6-b5d396a8ef03.png)

**Comment by SnoIcarus** [comment]
不行，我只有在单独加载AE2才能进去。@xsun2001
![1db8jw4g4 qk 44 v2f](https://cloud.githubusercontent.com/assets/25790174/23102609/22c84afe-f6e7-11e6-883e-12ce5c68991b.png)

你看看这个图，跟你的确实有点不一样，我好像还有个core
但是这个AE确实是从你这帖子里下的啊。我怕帖子下的有问题，特意来GitHub下，也一样

我不知道那个core是哪里来的，我确实只加载了AE2一个mod，也就是mods文件夹里就一个AE2，无其他的mod。

我单独加载神秘、神秘工匠，也可以进去。

AE2和神秘工匠同时加载就不行。。

API 是 1.7.10-LiteLoader1.7.10-1.7.10-Forge10.13.4.1614-1.7.10
或者我用单独的Forge10.13.4.1614进也不行
我也试了最稳定的ForgeForge10.13.4.1558，也是不行。。

**Comment by SnoIcarus** [comment]
我不知道那个core是哪里来的，我确实只加载了AE2一个mod，也就是mods文件夹里就一个AE2，无其他的mod。

我单独加载神秘、神秘工匠，也可以进去。

AE2和神秘工匠同时加载就不行。。

**Comment by xsun2001** [comment]
AE2的确自带一个叫core的mod，这在mod开发中叫核心mod，他可以在minecraft加载之前魔改java字节码。（反正是AE2自己的就好了）还有你那个版本为什么是rv3-alpha-0??

**Comment by SnoIcarus** [comment]
我不知道为什么是0阿。。文件确实是从这里下载阿，QAQ

**Comment by xsun2001** [comment]
好吧，我承认是我的问题。。。。我马上改。。难道就是因为这个才导致的问题？？

**Comment by SnoIcarus** [comment]
辛苦辛苦，我去给你帖子多评论多加分。
我现在也是上三年级，但是跟你不太一样，是中专第三年

**Comment by SnoIcarus** [comment]
可以的话，能不能加个Q，如果有问题还要向你请教 我现在在弄一个大型整合包 目标200个mod，
这是我的帖子http://www.mcbbs.net/thread-674261-1-1.html
还在测试版

**Comment by xsun2001** [comment]
非常乐意。qq:1563770452

**Comment by xsun2001** [comment]
试试这个
[appeng.zip](https://github.com/xsun2001/Applied-Energistics-2-Unofficial/files/785861/appeng.zip)

**Comment by SnoIcarus** [comment]
已加

**Comment by xsun2001** [comment]
不要再文件名中加中文。。。。。//血的教训

**Comment by MoeHero** [comment]
新版tt我也不知道从哪下载 我就是早下载完的= =修复了息壤的bug

**Comment by xsun2001** [comment]
不会TT弃坑了吧。。。。

**Comment by MoeHero** [comment]
应该弃坑了 我当时从某个ci上下载的现在已经无法访问了

**Comment by xsun2001** [comment]
最近MC版本迭代太快，压垮了一批mod制作者，莫非这是MC走向没落的前兆？反正我是不相信能有比1.7.10更有活力的版本了。哎。。。（话说jeb加羊驼是来逗逼的吗？？？）

**Comment by MoeHero** [comment]
1.10.2也还不错mod挺多 不过性能有些问题而且mod改动有些都不小

**Comment by SnoIcarus** [comment]
@MoeHero 能不能把你的版本传给我，
@xsun2001 我感觉MC有可能走向没落，只是有可能。
当年我还认为1.6.4是最完美的一个版本，也非常的有活力，为了接受1.7.10这个新版本花了不少时间
可是现在1.7.10往后确实更新的太快了，而且更新内容总是一些无关紧要的东西。。

**Comment by EverNife** [comment]
Sorry... but

English please :V

What was resolved about this ^^

**Comment by xsun2001** [comment]
@evernife I think my solution may be useful sometime,but it isn't the key of this issue. In fact,I didn't realize it was a bug before. I met this issue many days ago,with rv2-stable-10.I removed all the Chinese characters in the file name,and it worked! So I didn't think about it carefully,until now. Something hides in deep may cause it and I am trying to find it. It seems that some mod changed the byte code of AE2 before pre-init.If you have the same issue,please show your mods list and the whole log file of FML. The information we have,the better. I hope it will be resolved. I am sorry for this issue if it made you unhappy. I am sorry for my poor English too.

**Comment by xsun2001** [comment]
@evernife I think I find the problem. Some mod like ThaumicTinkerer  and ThaumicEnergtic packed the old AE2 api in its jar. So AE2 itself cannot work well with the old api. You can use any software like WinRAR open the AE2 mod jar and ThaumicTinkerer mods jar, and delete all files in appeng/api in the TT,then copy the new api from appeng/api in AE2's jar to appeng/api in TT's jar.You can do the same thing to any mod that have the old api. That will work. Hope you can understand my English.

**Comment by MoeHero** [comment]
卧槽 api还可以直接替换的？

**Comment by xsun2001** [comment]
Nothing is impossible.

**Comment by EverNife** [comment]
ty, i will give a try

**Comment by MoeHero** [comment]
也就是API接口没有变只是里面处理的类改了？

**Comment by xsun2001** [comment]
The [new version](https://github.com/xsun2001/Applied-Energistics-2-Unofficial/releases/tag/rv3.beta.8) or "rv3-beta-8" will solve this problem completely. You can try it without change the filename or the content of mod jar file. I hope it will work fine.
