### ISSUE TITLE
crash report 

### ISSUE THREAD

**Issue by JoeSGT** [xsun2001/Applied-Energistics-2-Unofficial#21]
```
Caused by: java.lang.NoSuchFieldError: air
	at appeng.util.Platform.<clinit>(Platform.java:121)
	at appeng.core.AELog.getLogger(AELog.java:58)
```
[crash-2018-11-14_11.49.34-client.txt](https://github.com/xsun2001/Applied-Energistics-2-Unofficial/files/2581730/crash-2018-11-14_11.49.34-client.txt)

I am not sure what happen but i had compile the latest commit https://github.com/xsun2001/Applied-Energistics-2-Unofficial/commit/6bac87e2c9f230e9b7b975c034fefb44cac78b19
and i use load up Minecraft then i crashed

**Comment by JoeSGT** [comment]
Looks like something went wrong with compiling i didn't know that there was already publicly compiled jar to the latest commit
