### ISSUE TITLE
NullPointerException on EntityGrowingCrystal

### ISSUE THREAD

**Issue by EverNife** [xsun2001/Applied-Energistics-2-Unofficial#23]
Some of my players are getting this crash when trey throw  quartz certus  on water 

```
java.lang.NullPointerException: Ticking entity
	at appeng.entity.EntityGrowingCrystal.func_70071_h_(EntityGrowingCrystal.java:75)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
Entire crash-report: https://paste.ubuntu.com/p/TTvmxmrCn8/

**Comment by EverNife** [comment]
i will send a pr when i get my workspace to work.

But just replacing the code with ```(this.boundingBox.minY + this.boundingBox.maxY)``` solves the problem!

**Comment by EverNife** [comment]
sorry, i forgot it :/

**Comment by xsun2001** [comment]
Nevermind. In fact, it is me who should be blamed. I am very grateful for your kind heart.
