### ISSUE TITLE
crash bug

### ISSUE THREAD

**Issue by haha370104** [xsun2001/Applied-Energistics-2-Unofficial#28]
It will crash when you try to use a ME Formation Plane to place another ME Formation Plane.

The crash report is like this

Time: 19-11-30 下午10:51
Description: Ticking GridNode

java.lang.ClassCastException: appeng.items.parts.ItemMultiPart cannot be cast to net.minecraft.item.ItemBlock
	at appeng.parts.automation.PartFormationPlane.injectItems(PartFormationPlane.java:481)
	at appeng.parts.automation.PartFormationPlane.injectItems(PartFormationPlane.java:73)
	at appeng.me.storage.MEPassThrough.injectItems(MEPassThrough.java:57)
	at appeng.me.storage.MEInventoryHandler.injectItems(MEInventoryHandler.java:106)
	at appeng.me.storage.NetworkInventoryHandler.injectItems(NetworkInventoryHandler.java:121)
	at appeng.me.cache.NetworkMonitor.injectItems(NetworkMonitor.java:155)
	at appeng.util.Platform.poweredInsert(Platform.java:1477)
	at appeng.parts.automation.PartImportBus.importStuff(PartImportBus.java:261)
	at appeng.parts.automation.PartImportBus.doBusWork(PartImportBus.java:213)
	at appeng.parts.automation.PartImportBus.tickingRequest(PartImportBus.java:166)
	at appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:91)
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43)
	at appeng.me.Grid.update(Grid.java:271)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:231)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_481_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

**Comment by xsun2001** [comment]
I'm really sorry for the delay. I'm also really sorry for the bug I created by mistake. I should check the code written by a senior high student twice. But there is a lot of thing to do before the next release version. There is less time than my expectation after entering the university.
